baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Willsoft'
cascade.description = "Welcome to Willsoft — The IT and software development company for companies of all sizes."

# Main navigation menu (order controlled by weight; lower weight appears first)
[[menu.main]]
name = "Services"
url = "/services/"
weight = 10

[[menu.main]]
name = "Products"
url = "/products/"
weight = 20

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 30

[[menu.main]]
name = "Innovation"
url = "/innovation/"
weight = 40

[[menu.main]]
name = "Courses"
url = "/courses/"
weight = 50

[[menu.main]]
name = "About Us"
url = "/about/"
weight = 60

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 70

[params]
googleAnalyticsID = 'G-NQ7H5WKFBM'
companyName = 'Willsoft'
twitterHandle = 'Willsoft_'
heroBaseClass = 'hero-default'
brandName = 'Willsoft'
logo = '/img/logo.svg'
cookieText = 'This site uses cookies to improve your experience and for advertising.'
cookieAcceptLabel = 'Accept all'
footerTypewriter = [
    'design the future 🚀',
    'design and build websites',
    'design software systems and architectures',
    'build full-stack web apps',
    'build native desktop apps',
    'build mobile apps',
    'build REST API:s',
    'build secure systems',
    'write robust software',
    'write scalable code',
    'write open-source software',
    'develop embedded systems',
    'develop new technologies',
    'work with relational databases',
    'work with no-SQL databases',
    'make PC and mobile games',
    'are a team of talented programmers',
    'can make all of your ideas come true',
    'can build whatever you want',
]

# Course categories configuration
[[params.courseCategories]]
id = "foundations"
title = "📚 Foundations"
accent = "blue"

[[params.courseCategories]]
id = "advanced"
title = "🚀 Advanced"
accent = "green"

[[params.courseCategories]]
id = "systems"
title = "🔍 Systems/Security"
accent = "yellow"

[[params.courseCategories]]
id = "research"
title = "🔬 Extensions/Research"
accent = "purple"

# Course fields configuration (academic/professional fields)
[[params.courseFields]]
id = "programming-languages"
title = "Programming Languages"
color = "#6366f1"

[[params.courseFields]]
id = "computer-systems"
title = "Computer Systems"
color = "#f59e0b"

[[params.courseFields]]
id = "security"
title = "Security"
color = "#ef4444"

[[params.courseFields]]
id = "formal-methods"
title = "Formal Methods"
color = "#8b5cf6"

[[params.courseFields]]
id = "ai-ml"
title = "AI/ML"
color = "#10b981"

[[params.courseFields]]
id = "parallel-computing"
title = "Parallel Computing"
color = "#06b6d4"

# Course data
[[params.courses]]
title = "Foundations of Programming Languages"
description = "Core principles of syntax, semantics, paradigms, and type systems, introducing how languages are defined and understood."
category = "foundations"
field = "programming-languages"

[[params.courses]]
title = "Foundations of Interpreters & Virtual Machines"
description = "How code executes via AST interpreters and bytecode VMs; stack vs. register machines and evaluation strategies."
category = "foundations"
field = "programming-languages"

[[params.courses]]
title = "Foundations of Compilers"
description = "Step-by-step compiler pipeline: lexing, parsing, semantic analysis, IR, optimization and code generation."
category = "foundations"
field = "programming-languages"

[[params.courses]]
title = "Advanced Language Theory, Design & Implementation"
description = "Advanced type systems, macros, effects, concurrency models, error handling, runtime architecture & ergonomics."
category = "advanced"
field = "programming-languages"
new = true

[[params.courses]]
title = "Advanced VMs & JIT Compilers"
description = "Virtual machine architectures, tiered & speculative JIT compilation, garbage collection & dynamic runtime optimization."
category = "advanced"
field = "programming-languages"

[[params.courses]]
title = "Advanced Compiler Construction & Optimization"
description = "SSA, data-flow, inlining, loop transforms, register allocation, polyhedral ideas & target-aware lowering."
category = "advanced"
field = "programming-languages"

[[params.courses]]
title = "Windows Internals (x86/x64)"
description = "Kernel → user architecture, processes, threads, memory management, drivers, system calls, scheduling, PE/COFF binaries & tooling."
category = "systems"
field = "computer-systems"

[[params.courses]]
title = "Systems Security"
description = "Exploits, vulnerabilities, mitigations, memory safety, attack surfaces, threat modeling, ROP, fuzzing, PWN, XSS, and more CTF-style topics."
category = "systems"
field = "security"
new = true

[[params.courses]]
title = "Compiler Security"
description = "Language-based security, memory safety, exploit classes in compilers/runtimes, supply chain risk, mitigations, secure toolchains, formal verification, proofs."
category = "systems"
field = "security"

[[params.courses]]
title = "Formal Methods & Proof Assistants"
description = "Logic foundations, proof automation & verification using Coq, Lean & Agda for language and compiler correctness."
category = "research"
field = "formal-methods"

[[params.courses]]
title = "Program Synthesis with Refinement Types"
description = "Guided synthesis using refinement types, holes, constraint solving & SMT-based search strategies."
category = "research"
field = "formal-methods"

[[params.courses]]
title = "AI-Assisted Programming & Synthesis"
description = "LLM-driven developer tooling, proof guidance, code generation & verified synthesis workflows."
category = "research"
field = "ai-ml"
new = true

[[params.courses]]
title = "E-Graphs & Equality Saturation"
description = "Algebraic rewrite engines, saturation strategies & global optimization for compilers and synthesizers."
category = "research"
field = "programming-languages"

[[params.courses]]
title = "Verified Compilers"
description = "End-to-end correctness (CompCert, CakeML), mechanized semantics & trusted computing bases."
category = "research"
field = "formal-methods"

[[params.courses]]
title = "Concurrency & Parallelism"
description = "Actors, CSP, STM, lock-free structures, GPU offload models & safe parallel runtime design."
category = "research"
field = "parallel-computing"

[[params.courses]]
title = "Metaprogramming & DSLs"
description = "Hygienic macros, multi-stage evaluation, staging runtimes & intentional language layering."
category = "research"
field = "programming-languages"

[[params.courses]]
title = "WebAssembly & Polyglot Runtimes"
description = "WASM execution model, embedding, cross-language interop & portability in modern ecosystems."
category = "research"
field = "programming-languages"

[[params.courses]]
title = "GPU/Accelerator Compilation"
description = "Passes for CUDA/OpenCL, heterogeneous lowering, scheduling, memory hierarchies & performance modeling."
category = "research"
field = "parallel-computing"

[[params.courses]]
title = "HoTT, Dependent & Refinement Types"
description = "Higher inductive types, path equality, expressive type-level reasoning & program correctness."
category = "research"
field = "formal-methods"

[[params.courses]]
title = "Quantum & Reversible Programming"
description = "Quantum state, reversible computation models, linear types & future runtime implications."
category = "research"
field = "parallel-computing"


[markup.asciidocExt]
safeMode = "unsafe"

[markup.goldmark.renderer]
unsafe = true
