baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Willsoft'
cascade.description = "Welcome to Willsoft — The IT and software development company for companies of all sizes."

[markup.asciidocExt]
safeMode = "unsafe"

[markup.goldmark.renderer]
unsafe = true
